### ISSUE TITLE
Uncaught exception 'PhpZenfolioException' with message 'File doesn't exist:

### ISSUE THREAD

**Issue by gilbermudez** [lildude/phpZenfolio#10]
Hi, I am using the upload method , but it returns an error.

I will leave a piece of code where I am using this method as well as the error
returned in the browser.

Here's the code I'm using:

error_reporting(E_ALL);
ini_set('display_errors', 1);

require_once("phpZenfolio.php");
$f = new phpZenfolio(array("AppName"=>"gbnuevo", "APIVer" => "1.6"));

$f->login("Username=******", "Password=******");

$news = $f->upload("PhotoSetId=404731699",
"File=/images/Tomorrowland_2014.jpg");

echo json_encode($news);

This is the error returned in the browser:

Fatal error: Uncaught exception 'PhpZenfolioException' with message 'File
doesn't exist: /images/Tomorrowland_2014.jpg' in
/Library/WebServer/Documents/pruebaZenfolio/phpZenfolio.php:512 Stack trace:
#0 /Library/WebServer/Documents/pruebaZenfolio/zenPrueba.php(10):
phpZenfolio->upload('PhotoSetId=4047...', 'File=/images/To...') #1 {main}
thrown in /Library/WebServer/Documents/pruebaZenfolio/phpZenfolio.php on line
512

they could tell me this error refers to ?

obviously the images folder and image exist in the project .

**Comment by lildude** [comment]
Sorry about the heeaaaaawwg delay in getting back to you; I accidentally stopped watching my own repo so haven't been getting the notifications. :blush:.

Please let me know if this is still a problem.

**Comment by lildude** [comment]
No follow up. Closing. Please feel free to reopen if this is still an issue.
