### ISSUE TITLE
Error for method LoadGroupHierarchy

### ISSUE THREAD

**Issue by ssalcor** [lildude/phpZenfolio#12]
I am using PHP pages fro this path: http://phpzenfolio.com/download, folder name PHPZenfolio 1.2
I am receiving this error message:

Zenfolio API Error for method LoadGroupHierarchy: E_NOSUCHOBJECT (Error Code: 90009) 

I tried to use “APIVer=1.8” but no change in the error. Any ideas?

**Comment by lildude** [comment]
Sorry about the delay in getting back to you, for some reason I've unsubscribed from my own repo :blush:

The error you're getting is coming from the Zenfolio API itself and suggests the object you're calling doesn't exist.  

Can you please provide a small snippet of code that caused this issue.

On a side note, someone did mention to me that you need to always use `APIVer=1.8` now and that you need to add `|| $this->APIVer == '1.8'` to line 549.  I've not had the chance to test of validate this but it worked for them.

**Comment by lildude** [comment]
Oh yes, I forgot to mention, this issue was previously encountered by someone else in https://github.com/lildude/phpZenfolio/issues/6

Make sure you are using your username, and not your email address for the `LoadGroupHierachy()` call as demonstrated in https://github.com/lildude/phpZenfolio/issues/6

**Comment by ssalcor** [comment]
Hi,

I looked up this posts before and non worked. I set up APIVer  to 1.8 and added $this->APIVer == '1.6' || and non worked. Here is my code:

<? PHP
$appname = 'My Cool App/1.0 (http://my.url.com)';
$username = ‘xxxxxxxxxx';
$password = ‘xxxxxxxxxx';

try {
/*
$f = new phpZenfolio("AppName={$appname}", "APIVer=1.8");
// Get list of recent galleries and collections
*/
$f = new phpZenfolio("AppName={$appname}");
// Login. As Plaintext is not passed, the challenge-response authentication method is used.
$f->login("Username={$username}", "Password={$password}");
$h = $f->LoadGroupHierarchy($username);
// Now traverse the tree and locate the first public gallery and display it's first 100 photos
array_walk($h['Elements'], 'displayImgs', $f);
}
catch (Exception $e) {
echo "{$e->getMessage()} (Error Code: {$e->getCode()})";
}

function displayImgs($element, $key, $f) {
if ( $element['$type'] == 'Group' ) {
array_walk($element['Elements'], 'displayImgs', $f);
} else {
if ( $element['PhotoCount'] > 0 ) {
$pictures = $f->LoadPhotoSetPhotos($element['Id'], 0, 100 );
// Display the 60x60 cropped thumbnails and link to the photo page for each.
foreach ($pictures as $pic) {
echo '<a href="',$pic['PageUrl'],'"><img src="',phpZenfolio::imageUrl($pic, 1),'" title="',$pic['Title'],'" alt="',$pic['Id'],'" /></a>';
}
break;
}
}
}
?>


On Apr 14, 2016, at 12:25 PM, Colin Seymour <notifications@github.com<mailto:notifications@github.com>> wrote:


Oh yes, I forgot to mention, this issue was previously encountered by someone else in #6<https://github.com/lildude/phpZenfolio/issues/6>

Make sure you are using your username, and not your email address for the LoadGroupHierachy() call as demonstrated in #6<https://github.com/lildude/phpZenfolio/issues/6>

**Comment by ssalcor** [comment]
I forgot to mention, I have 2 galleries in Zenfolio and I wonder why it can not see any of them.


On Apr 14, 2016, at 3:18 PM, Suha Alhabaj <alhabaj@wisc.edu<mailto:alhabaj@wisc.edu>> wrote:

Hi,

I looked up this posts before and non worked. I set up APIVer  to 1.8 and added $this->APIVer == '1.6' || and non worked. Here is my code:

<? PHP
$appname = 'My Cool App/1.0 (http://my.url.com<http://my.url.com/>)';
$username = ‘xxxxxxxxxx';
$password = ‘xxxxxxxxxx';

try {
/*
$f = new phpZenfolio("AppName={$appname}", "APIVer=1.8");
// Get list of recent galleries and collections
*/
$f = new phpZenfolio("AppName={$appname}");
// Login. As Plaintext is not passed, the challenge-response authentication method is used.
$f->login("Username={$username}", "Password={$password}");
$h = $f->LoadGroupHierarchy($username);
// Now traverse the tree and locate the first public gallery and display it's first 100 photos
array_walk($h['Elements'], 'displayImgs', $f);
}
catch (Exception $e) {
echo "{$e->getMessage()} (Error Code: {$e->getCode()})";
}

function displayImgs($element, $key, $f) {
if ( $element['$type'] == 'Group' ) {
array_walk($element['Elements'], 'displayImgs', $f);
} else {
if ( $element['PhotoCount'] > 0 ) {
$pictures = $f->LoadPhotoSetPhotos($element['Id'], 0, 100 );
// Display the 60x60 cropped thumbnails and link to the photo page for each.
foreach ($pictures as $pic) {
echo '<a href="',$pic['PageUrl'],'"><img src="',phpZenfolio::imageUrl($pic, 1),'" title="',$pic['Title'],'" alt="',$pic['Id'],'" /></a>';
}
break;
}
}
}
?>


On Apr 14, 2016, at 12:25 PM, Colin Seymour <notifications@github.com<mailto:notifications@github.com>> wrote:


Oh yes, I forgot to mention, this issue was previously encountered by someone else in #6<https://github.com/lildude/phpZenfolio/issues/6>

Make sure you are using your username, and not your email address for the LoadGroupHierachy() call as demonstrated in #6<https://github.com/lildude/phpZenfolio/issues/6>

**Comment by lildude** [comment]
I've tested your code, with a tweak to remove the `break;` and it definitely works for me:

```php
<?php

require_once("../phpZenfolio.php");

$appname = 'My Cool App/1.0 (http://my.url.com)';
$username = 'colinseymour';
$password = '[redacted]';

try {
  /*
  $f = new phpZenfolio("AppName={$appname}", "APIVer=1.8");
  // Get list of recent galleries and collections
  */
  $f = new phpZenfolio("AppName={$appname}");
  // Login. As Plaintext is not passed, the challenge-response authentication method is used.
  $f->login("Username={$username}", "Password={$password}");
  $h = $f->LoadGroupHierarchy($username);
  // Now traverse the tree and locate the first public gallery and display it's first 100 photos
  array_walk($h['Elements'], 'displayImgs', $f);
}
  catch (Exception $e) {
  echo "{$e->getMessage()} (Error Code: {$e->getCode()})";
}

function displayImgs($element, $key, $f) {
  if ( $element['$type'] == 'Group' ) {
    array_walk($element['Elements'], 'displayImgs', $f);
  } else {
    if ( $element['PhotoCount'] > 0 ) {
      $pictures = $f->LoadPhotoSetPhotos($element['Id'], 0, 100 );
      // Display the 60x60 cropped thumbnails and link to the photo page for each.
      foreach ($pictures as $pic) {
        echo '<a href="',$pic['PageUrl'],'"><img src="',phpZenfolio::imageUrl($pic, 1),'" title="',$pic['Title'],'" alt="',$pic['Id'],'" /></a>';
      }
    }
  }
}
?>
```

... produces (I've only got two public images) ...

![screen shot 2016-04-15 at 10 06 06](https://cloud.githubusercontent.com/assets/627280/14556780/be398ce0-02f1-11e6-9f5d-ef087fa8abb3.png)

... without any errors.

With a slight variation on the explanation in #6, the only way I can get your error is if I change `$username = 'colinseymour';` to the email address used to register on Zenfolio, ie `$username = 'lildood@gmail.com';`

Are you definitely setting `$username` to the username as it appears in the menu bar at the top-right of your Zenfolio dashboard?  ie are you setting it to whatever appears here:

![zenfolio___dashboard](https://cloud.githubusercontent.com/assets/627280/14556004/c2457a32-02ed-11e6-8dbe-5c3382348fe6.png)

... when you sign into Zenfolio?

If you are, do you still get the same error if you take phpZenfolio out of the equation entirely and query the API directly using curl with:

```
$ export username="[your_url_encoded_username]"
$ export password="[your_url_encoded_password]"
$ export token=$(curl -s "https://api.zenfolio.com/api/1.8/zfapi.asmx/AuthenticatePlain" -d "loginName=$username" -d "password=$password" | sed -n 's/.*>\(.*[^<]\)<\/string>/\1/p')
$ curl -H "X-Zenfolio-Token: $token" "https://api.zenfolio.com/api/1.8/zfapi.asmx/LoadGroupHierarchy?loginName=$username"
```

If you do, then you'll need to contact Zenfolio for further assistance as this curl command proves this is not a problem with phpZenfolio and more likely a problem with your account on Zenfolio or the information you're passing to the API.

On a side note, I updated phpZenfolio last night to default to using the 1.8 API.

**Comment by ssalcor** [comment]
Hi,

I have not heard back from you about this?



On Apr 14, 2016, at 3:18 PM, Suha Alhabaj <alhabaj@wisc.edu<mailto:alhabaj@wisc.edu>> wrote:

Hi,

I looked up this posts before and non worked. I set up APIVer  to 1.8 and added $this->APIVer == '1.6' || and non worked. Here is my code:

<? PHP
$appname = 'My Cool App/1.0 (http://my.url.com<http://my.url.com/>)';
$username = ‘xxxxxxxxxx';
$password = ‘xxxxxxxxxx';

try {
/*
$f = new phpZenfolio("AppName={$appname}", "APIVer=1.8");
// Get list of recent galleries and collections
*/
$f = new phpZenfolio("AppName={$appname}");
// Login. As Plaintext is not passed, the challenge-response authentication method is used.
$f->login("Username={$username}", "Password={$password}");
$h = $f->LoadGroupHierarchy($username);
// Now traverse the tree and locate the first public gallery and display it's first 100 photos
array_walk($h['Elements'], 'displayImgs', $f);
}
catch (Exception $e) {
echo "{$e->getMessage()} (Error Code: {$e->getCode()})";
}

function displayImgs($element, $key, $f) {
if ( $element['$type'] == 'Group' ) {
array_walk($element['Elements'], 'displayImgs', $f);
} else {
if ( $element['PhotoCount'] > 0 ) {
$pictures = $f->LoadPhotoSetPhotos($element['Id'], 0, 100 );
// Display the 60x60 cropped thumbnails and link to the photo page for each.
foreach ($pictures as $pic) {
echo '<a href="',$pic['PageUrl'],'"><img src="',phpZenfolio::imageUrl($pic, 1),'" title="',$pic['Title'],'" alt="',$pic['Id'],'" /></a>';
}
break;
}
}
}
?>


On Apr 14, 2016, at 12:25 PM, Colin Seymour <notifications@github.com<mailto:notifications@github.com>> wrote:


Oh yes, I forgot to mention, this issue was previously encountered by someone else in #6<https://github.com/lildude/phpZenfolio/issues/6>

Make sure you are using your username, and not your email address for the LoadGroupHierachy() call as demonstrated in #6<https://github.com/lildude/phpZenfolio/issues/6>

**Comment by lildude** [comment]
@ssalcor I'm waiting to hear back from you in response to https://github.com/lildude/phpZenfolio/issues/12#issuecomment-210385085

**Comment by ssalcor** [comment]
I removed break; from the code and still receiving the same error.
How do I use the commands you mentioned:
$ export username="[your_url_encoded_username]"
$ export password="[your_url_encoded_password]"
$ export token=$(curl -s "https://api.zenfolio.com/api/1.8/zfapi.asmx/AuthenticatePlain" -d "loginName=$username" -d "password=$password" | sed -n 's/.*>\(.*[^<]\)<\/string>/\1/p')
$ curl -H "X-Zenfolio-Token: $token" "https://api.zenfolio.com/api/1.8/zfapi.asmx/LoadGroupHierarchy?loginName=$username"

I mean do I put them in php file or txt or what?

**Comment by lildude** [comment]
The `break;` is _not_ what is causing your problem.  The value you are entering for the `$username` is the most likely place things are wrong.

As for those commands, you would need to run them within a terminal window on a Linux or OS X machine.

If you've got GitHub Desktop installed on a Windows machine, it comes with something called "Git Bash" which will also give you a shell prompt which you may be able to run these commands on.

I've only tested these commands on OS X so your usage may vary on other operating systems.

**Comment by lildude** [comment]
Oh yes, and you'd need to replace `[your_url_encoded_username]` and `[your_url_encoded_password]` with the appropriate values for your user account.

**Comment by ssalcor** [comment]
I am sorry for being difficult but I am really not familiar with terminal on OS X. I tried the commands one by one, and when I reached this:
 export token=$(curl -s "https://api.zenfolio.com/api/1.8/zfapi.asmx/AuthenticatePlain" -d "loginName=$username" -d "password=$password" | sed -n 's/.>(.[^<])<\/string>/\1/p')
It changed the cursor from $ to >. I believe this is an editor to write commands. I entered the next command:
$ curl -H "X-Zenfolio-Token: $token" "https://api.zenfolio.com/api/1.8/zfapi.asmx/LoadGroupHierarchy?loginName=$username"

I do not know what to do next or what to expect as output??

**Comment by lildude** [comment]
If you're using OS X, the following steps should do the trick:

1.  Open Terminal.app
2.  Type: `bash` and press enter/return.
3.  Type my previous commands exactly as I originally wrong them, pressing enter/return after each, but _without_ the `$` at the beginning of each line.  That is a prompt indicator and shouldn't be typed.  Don't remove any other `$` sign. Be sure to replace `[your_url_encoded_username]` and `[your_url_encoded_password]` with appropriate values.
4. If you hit the same error as you do with phpZenfolio, you'll see it in the output similar to the following (the faultstring may be slightly different):

```
$ curl -H "X-Zenfolio-Token: $token" "https://api.zenfolio.com/api/1.8/zfapi.asmx/LoadGroupHierarchy?loginName=$username"

<?xml version="1.0" encoding="utf-8"?><Fault xmlns:zf="http://www.zenfolio.com/api/1.8"><faultcode>zf:E_NOSUCHOBJECT</faultcode><faultstring>50018: There is no such folder.</faultstring><detail /></Fault>%
$
```

If this command succeeds, you'll get a load more XML.

If in doubt, feel free to paste the output from the last command into this issue.

**Comment by ssalcor** [comment]
Here is what I got:

<?xml version="1.0" encoding="utf-8"?><Fault xmlns:zf="http://www.zenfolio.com/api/1.8"><faultcode>zf:E_NOSUCHOBJECT</faultcode><faultstring>50018: There is no such folder.</faultstring><detail /></Fault>My user name-mbpr:~

**Comment by ssalcor** [comment]
So I have to contact Zenfolio!!?

**Comment by lildude** [comment]
Yup. You've removed phpZenfolio from the equation and are querying the API directly. There's something it doesn't like about your query. Zenfolio would be the best to determine what. 

Let me know how it goes.

**Comment by ssalcor** [comment]
Thanks a lot for your help. I contacted Zenfolio, and I am waiting for their response.

**Comment by lildude** [comment]
@ssalcor any news from Zenfolio?

**Comment by lildude** [comment]
@Salhabaj any new from Zenfolio?

**Comment by Salhabaj** [comment]
Nothing new. We have dropped the project. It support at Zenfolio reported that they gave us the privileges we needed, but the error messages did not disappear. So, we dropped the project because nothing was working with logging in and it was time consuming to get the necessary support.

**Comment by lildude** [comment]
That's disappointing 😢 .  Thanks for letting me know.
