### ISSUE TITLE
Please update documentation and any calls to the API to call API version 1.8

### ISSUE THREAD

**Issue by ZappCatt** [lildude/phpZenfolio#13]
Thanks for your reply to the Tweet from Zenfolio. This is the issue which they had contacted you about.

Zenfolio has deprecated API 1.6, so any calls to that API will error out.

I noticed on your documentation at: http://phpzenfolio.com/docs/ 

APIVer - Optional
Default: 1.6

Use this to set the endpoint you wish to use. The default is 1.6 as this
is the latest endpoint provided by Zenfolio.

If there are any example code snippets which use this API version call, they will fail also.

Thanks.

**Comment by lildude** [comment]
Thanks ZappCatt. I've been meaning to do this for a while. I plan to release a new version in the next few days just to update the defaults to the 1.8 API, with corresponding docs updates, as this is the only change needed and the only thing people have contacted me about recently.

I plan a major rewrite in the not-too-distant future too.

**Comment by lildude** [comment]
Done!  It didn't take long at all so I did it this evening.

Closing this ticket as phpZenfolio 1.3 is now available and defaults to using the 1.8 API.  The docs have been updated too.

**Comment by ZappCatt** [comment]
Excellent! Thanks!
