### ISSUE TITLE
Not able to download the Zenfolio Original images

### ISSUE THREAD

**Issue by NagarajanSekar** [lildude/phpZenfolio#15]
Hi,

I am using phpZenfolio 1.3 and I am able to authenticate and getting resized images by calling corresponding functions.
But I am NOT able to download the Original images and instead I am getting the image with content as 'Content Protected by Owner'.

Here is the process which i followed.

I followed the below link and got the knowledge how to download the Original images through Zenfolio PHP wrapper.
https://www.zenfolio.com/zf/help/api/guide/download

Code snippet:

1. main.php

function checkZenfolioOriginalImageDownload() {
       
        $url = getImagesOnToken(TOKEN, ID, 1);       
        $fileName = WEDDING_IMG_PATH_MAIN.'test/originalImage1.jpg';
        $contents = file_get_contents($url);
        $fp = fopen($fileName, 'w+');
        fwrite($fp, $contents);
        fclose($fp);
        system('chmod -R 777 '.$fileName);
        exit;
       

    }

2. getImageUrl.php

function getImagesOnToken($checkAuth, $galId, $photoCount) {
        require_once '../webroot/phpZenfolio.php';
        $appName = 'testApp.zenfolio.com';
        $f = new phpZenfolio("AppName={$appName}");
        try {
       
            $f->setAuthToken($checkAuth);  // $checkAuth - password token           
            $photos = $f->LoadPhotoSetPhotos($galId, 0, $photoCount);
           
            $photoIdArray = array();
            foreach($photos as $photoItem) {
                $photoIdArray[] = $photoItem['Id'];
            }
            $originalKey = $f->GetDownloadOriginalKey($photoIdArray, $checkAuth); // $checkAuth - password token

            $originalImageUrl = phpZenfolio::imageUrl($photos, 1, $originalKey, 'original');
            return originalImageUrl;

         } catch (Exception $e) {
            $r['status'] = false;
            $r['error'] = $e->getMessage();
            echo json_encode($r);
            exit;
            echo "{$e->getMessage()} (Error Code: {$e->getCode()})";
        }

}

3. phpZenfolio.php      (version 1.3)

    public static function imageUrl( $photo, $size, $originalKey, $showType ) {
         
             if ($showType == 'show') {
                 return "http://{$photo['UrlHost']}/{$photo['UrlCore']}-{$size}.jpg?sn={$photo['Sequence']}&tk={$photo['UrlToken']}";
             } else {
                 // Returning original image url
                 return $photo['OriginalUrl']."?key=".$originalKey;
             }
                
     }
 
RESULT :  Original url

http://nagarajan.zenfolio.com/img/s11/v28/p2129545206.jpg?key=nTaE0lylIh-YUj_Lv-mA_NNxgjrExcqwgBzYgzG--VboMUEKSBuchkfx18M2brh5K0FmrlZtzReIi7e-V_9k0g==

The issue is that the above URL displaying the original image on the browser BUT the image not getting downloaded into the system as per the code (1. main.php), instead its displaying "Content Protected by Owner".

I hope that you can understand the process and issues occurred. Please help me to sorted this out.

Thank you.

**Comment by lildude** [comment]
I suspect you're hitting this problem because you're not passing an authentication token with your request to download the file and the image is a private image.  

To quote the docs:

> Note that the download key does not replace the authentication token. If the photo itself is not public, a valid authentication token has to be provided in the request in order to successfully download the original image.

I can see you passing the key, but nothing is passing the required auth token.

The image is probably displaying correctly in your browser without an explicit token because you're already authenticated against Zenfolio in that session. I wouldn't expect the image URL to work in an incognito mode/private browsing window/tab or for anyone else who doesn't have access to the image - I get the "Content protected by owner" image if I attempt to view the URL you included.

Setting the `X-Zenfolio-Token` header with your auth token obtained from authentication should allow you to download the original image.

As you're using `file_get_contents()`, you can find an example on how to set the headers at http://stackoverflow.com/questions/2107759/php-file-get-contents-and-headers .

Let me know how it goes.

**Comment by NagarajanSekar** [comment]
Thanks for your response.
https://www.zenfolio.com/zf/help/api/guide/download
The above link says that the downloaded key should be passed like below : 
http://demo.zenfolio.com/img/v0/p340540780.jpg?key=50B80FB0A7554ab

As per your suggestion how can i pass the authentication token into it. I mean in what format I should pass it?

**Comment by lildude** [comment]
> The above link says that the downloaded key should be passed like below : 
> http://demo.zenfolio.com/img/v0/p340540780.jpg?key=50B80FB0A7554ab

Indeed, and you're doing this already.  But as the documentation says, you need to send the auth token _too_, which means setting the `X-Zenfolio-Token` header with the token in your `file_get_contents()` call as demonstrated at http://stackoverflow.com/questions/2107759/php-file-get-contents-and-headers  

phpZenfolio sets this header automatically for you for any request made using the instantiated object if the auto token is set (see [phpZenfolio.php#L356-L358](https://github.com/lildude/phpZenfolio/blob/master/phpZenfolio.php#L356-L358)).  As you're downloading the file outside of the instantiated object, you need to do this yourself.

For example (untested so you may need to tweak it a bit), 

```php
function checkZenfolioOriginalImageDownload() {
    // Define the stream options to pass the token in the HTTP request headers
    $opts = array(
        'http'=>array(
            'method'=>'GET',
            'header'=>"X-Zenfolio-Token: $checkAuth\r\n"
        )
    );
    // Create the stream
    $context = stream_context_create($opts);

    $url = getImagesOnToken(TOKEN, ID, 1);       
    $fileName = WEDDING_IMG_PATH_MAIN.'test/originalImage1.jpg';
    // Download the file using the stream context
    $contents = file_get_contents($url, false, $context);
    $fp = fopen($fileName, 'w+');
    fwrite($fp, $contents);
    fclose($fp);
    system('chmod -R 777 '.$fileName);
    exit;
}
```

I've not tested this, but it should do the trick.

**Comment by NagarajanSekar** [comment]
Thanks for your suggestion.
Its Cool. 
I am able to download original images now.

**Comment by lildude** [comment]
Great! Gonna close this issue now.
