### ISSUE TITLE
Error with LoadGroupHierarchy and LoadPublicProfile (possibly others)

### ISSUE THREAD

**Issue by cmdraper** [lildude/phpZenfolio#16]
I wasn't sure whether to open a new issue, or post to the closed issue #12 as it's the same problem.  Using the examples, I am getting the E_NOSUCHOBJECT error when hitting the LoadGroupHierarchy method (I've also tried with LoadPublicProfile, and get the same exception.  I'm guessing some others would as well, but those are the two I've tried.)

I am definitely using the username and not email, and it appears to be logging in alright, as I am getting an authToken.  Also, I am able to access images and upload an image to a photoset (so not all methods are affected.)

I tried contacting Zenfolio support, and they mentioned I should contact you.  Their exact response was:

> Thank you for your patience while this was sent over for further investigation.
> 
> You mention that you are interfacing with the Zenfolio API through the third party tool, phpZenfolio Wrapper. We would suggest you contact the developer of that tool to see if he is working on any known issues with the LoadGroupHierarchy and LoadPublicProfile access via his tool.
> 
> If there are any issues, he will work with our engineers to get them fixed.
> 
> Thanks, 
> 
> Zack | Zenfolio Customer Support
> Visit our Online Support Center 

Below is the contents of my modified example-login.php file.  The only difference is I have added the appname, username, and password (removed from the pasted code.)  I have also added some debugging commands to isolate where the problem was, and it breaks before the third var_dump (during the call to LoadGroupHierarchy.)  Results can be seen here: [REDACTED].

```<?php
/**
 * Copyright (c) 2010 Colin Seymour
 *
 * This file is part of phpZenfolio.
 *
 * phpZenfolio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * phpZenfolio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with phpZenfolio.  If not, see <http://www.gnu.org/licenses/>.
 */
?>
<html>
<head>
	<title>phpZenfolio Login Example</title>
	<style type="text/css">
		body { background-color: #fff; color: #444; }
		div { width: 600px; margin: 0 auto; text-align: center; }
		img { border: 0;}
	</style>
</head>
<body>
	<div>
		<a href="http://phpzenfolio.com"><img src="phpZenfolio-logo.png" /></a>
		<h2>phpZenfolio Login Example</h2>
<?php
/* Last updated with phpZenfolio 1.0
 *
 * This example file shows you how to login and display all the images of the your
 * first photoset or collection, regardless of whether it's public or not.
 *
 * You'll need to set the following:
 * - $appname to your application name, version and URL
 * - $username to your Zenfolio username
 * - $password to your user's password
 *
 * The application name and version is required, but there is no required format.
 * See the README.txt for a suggested format.
 *
 * You can see this example in action at http://phpzenfolio.com/examples/
 */
require_once("../phpZenfolio.php");

$appname = 'My Cool App/1.0 (http://my.url.com)';
$username = 'webmstreagleeye';
$password = '[redacted]';


try {
	$f = new phpZenfolio("AppName={$appname}", "APIVer=1.8");
echo("<h2>Initialized Zenfolio object:</h2><p>");
var_dump($f);
echo("</p><h3>Logging in...</h3>");
	// Login. As Plaintext is not passed, the challenge-response authentication method is used.
	$f->login("Username={$username}", "Password={$password}");
echo("<h2>Logged-in Zenfolio object:</h2><p>");
var_dump($f);
echo("</p><h3>Loading hierarchy...</h3>");
	// Load the User's hierachy
	$h = $f->LoadGroupHierarchy($username);
echo("<h2>Group Hierarchy:</h2><p>");
var_dump($h);
echo("</p>");
	// Load the photos for the first set/collection
	$photos = $f->LoadPhotoSetPhotos($h['Elements'][0]['Id'], 0, $h['Elements'][0]['PhotoCount']);
	// Display the 60x60 cropped thumbnails and link to the image page for each image in the first gallery/collection.
	foreach ($photos as $photo) {
		echo '<a href="',$photo['PageUrl'],'"><img src="',phpZenfolio::imageUrl($photo, 1),'" title="',$photo['Title'],'" alt="',$photo['Id'],'" /></a>';
	}
}
catch (Exception $e) {
	echo "{$e->getMessage()} (Error Code: {$e->getCode()})";
}
?>
	</div>
</body>
</html>
```

**Comment by lildude** [comment]
Hmmm, I still think this is something on the Zenfolio side of things - I suspect there's a setting or requirement on their side that isn't being met on your and other's accounts which doesn't affect mine. 

Let's take phpZenfolio out of the equation entirely. What happens if you use curl to query the API directly as I suggested in https://github.com/lildude/phpZenfolio/issues/12 ? 

Run this in a terminal:

```
$ export username="[your_url_encoded_username]"
$ export password="[your_url_encoded_password]"
$ export token=$(curl -s "https://api.zenfolio.com/api/1.8/zfapi.asmx/AuthenticatePlain" -d "loginName=$username" -d "password=$password" | sed -n 's/.*>\(.*[^<]\)<\/string>/\1/p')
$ curl -H "X-Zenfolio-Token: $token" "https://api.zenfolio.com/api/1.8/zfapi.asmx/LoadGroupHierarchy?loginName=$username"
```

What do you get in response?

**Comment by lildude** [comment]
On a side note, I've edited your original comment to remove the link to your demo as you were exposing your private generated auth token.

**Comment by cmdraper** [comment]
Thanks for the reply and for your help on this (in addition to the GREAT wrapper!)  I think you're right about it being an account issue on the Zenfolio side.  When I run the commands on the command line, I still get the E_NOSUCHOBJECT error.  Thinking it over some more, I believe that the problem is that the account we were trying to use through the API was a "partner" account added by the owner for the purposes of web access.  I think certain functions will only work with the actual owner account, as I created a trial account (so I would be owner) and the methods work fine.  I thought "partner" would have the same access, but apparently not.  (I'll reply back to Zenfolio.)

This issue can be closed.  It would be nice to have it working, but for our current project, the methods that do work with this account are quite sufficient.

Thanks for the help, and for removing the link to my demo page. :-)  I have taken the page down now, as I think there is nothing more to be done here.

**Comment by lildude** [comment]
Bingo!!! The partner account is definitely the information I was missing and didn't even know existed 😀. The more restrictive permissions of a partner account make sense and would explain the inability to load the whole group hierarchy - the partner is probably only granted access to a portion of the hierarchy.

I'm in the process of completely rewriting phpZenfolio to bring it into the modern world and will definitely document this and maybe see if I can detect such accounts.

Thanks for digging into this from your side too.

/cc @ssalcor - I suspect you may also have a partner account, hence your problems in #12
