### ISSUE TITLE
How to Check whether the User Token is Valid or Not.

### ISSUE THREAD

**Issue by NagarajanCerulean** [lildude/phpZenfolio#19]
Hi,

This is Nagarajan, 
I am using the phpZenfolio.php 1.3.

I am doing the Authentication by calling the function ->**login($username, $password)** and keeping the username and generated Token in the Database.

If the user logins at second time, I will fetch the username and Token from our database. And will call the corresponding functions ->**setAuthToken($dbToken)** and ->**LoadGroupHierarchy($dbUsername)** for getting the Zenfolio albums. Here I am not checking whether the existing Token is Valid or not. But This is necessary to check here.

I have referred the document but I couldn't find it. I request you to provide the specific function for checking whether the existing token is valid or not OR Authentication by using Token alone.

Thank you,
Nagarajan

**Comment by lildude** [comment]
The authentication token is only valid for slightly more than 24 hours as documented right at the end of the page at http://www.zenfolio.com/zf/help/api/guide/auth:

> The authentication token is only valid for slightly more than 24 hours. If you expect your application to run for longer than 24 hours, it needs to periodically reauthenticate to obtain a fresh authentication token.

I don't think the Zenfolio API provides a method of determining if a token is still valid short of attempting to use it - I recommend you review the [API docs](http://www.zenfolio.com/zf/help/api) or contact Zenfolio if you want to be 100% sure.  

A better solution would be to keep track of when the authentication token was received when you store it in your database and then check when it is reused.  If this is more than 24hours later, you're safer re-authenticating and getting a new token.
