### ISSUE TITLE
Get images url

### ISSUE THREAD

**Issue by aninditaelagoon** [lildude/phpZenfolio#21]
Hello,
Need a help in Zenfolio. Need to get the image url.
For example
http://www.zenfolio.com/cdn/pub/6rhr1mgujado/0/null/m/kd9huj2ukkmjnzvx2t6y/s7/v165/p2381501363-3.jpg?ts=6VH&tk=33XfJjt33Doahj8eJht_fzXm2gP5K0kMoog0BqgEvkE=

http://www.zenfolio.com/cdn/pub/6rhr1mgujado/0/null/m/nsfnersapkgxix9uexzy/s6/v144/p2412163861-2.jpg?ts=6VH&tk=r1Mq964lmETFBXJ62P7lsMhZ0kWoROPAXxRsMpb-Gf0=

in the above url  from ‘p2381501363-3.jpg’ and p2412163861-2.jpg, photo id is ‘2381501363’ and ‘2412163861’. But how the other part of url is created? Do you have any documentation of how the image url is created.

I will be helpfull, if you let me know.

**Comment by lildude** [comment]
> Need a help in Zenfolio. Need to get the image url.
> For example
> http://www.zenfolio.com/cdn/pub/6rhr1mgujado/0/null/m/kd9huj2ukkmjnzvx2t6y/s7/v165/p2381501363-3.jpg?ts=6VH&tk=33XfJjt33Doahj8eJht_fzXm2gP5K0kMoog0BqgEvkE=
> 
> http://www.zenfolio.com/cdn/pub/6rhr1mgujado/0/null/m/nsfnersapkgxix9uexzy/s6/v144/p2412163861-2.jpg?ts=6VH&tk=r1Mq964lmETFBXJ62P7lsMhZ0kWoROPAXxRsMpb-Gf0=

You're in luck, phpZenfolio has a helper function to make this easier for you - see https://github.com/lildude/phpZenfolio/blob/master/docs/other.md#image-urls-helper

If you want to see how this is constructed, you can see the function at https://github.com/lildude/phpZenfolio/blob/master/lib/phpZenfolio/Client.php#L270-L284

**Comment by lildude** [comment]
I think I can take the lack of further updates as confirmation I've answered your question. Feel free to reopen if I haven't.
