### ISSUE TITLE
Need to know the appname

### ISSUE THREAD

**Issue by aninditaelagoon** [lildude/phpZenfolio#22]
In zenfolio, I am working in http://monicahahnphotography.com. From where I will get the below one
$appname = 'YOUR_APP_NAME/VER (URL)'; ?

**Comment by lildude** [comment]
That would the name of your application/site/whatever that you are coding with the help of phpZenfolio.

This is there so Zenfolio know who to contact if they find an application abusing their API.

**Comment by aninditaelagoon** [comment]
Thanks for your reply. I have given the below one.
$appname = 'monicahahnphotography/1.8 (http://dev1.elagoondigital.net/monicahahnphotography/php/)';

My url in which I am working is http://dev1.elagoondigital.net/monicahahnphotography/php/
Still getting the below error
![image](https://user-images.githubusercontent.com/30255045/28307810-c391c4c0-6bc1-11e7-9c98-561f26532f97.png)

**Comment by lildude** [comment]
That's not likely to be related to your application name as the error you are seeing is coming from Zenfolio, not phpZenfolio.  I suspect it may be coming from one of the calls after the login in this section https://github.com/lildude/phpZenfolio/blob/3b90874078ab8a22e2585065f1b586c7d71bce94/examples/example-login.php#L46-L51

Try commenting them all out and uncomment one at a time until you find the call that is producing the error.  

Please also keep in mind that if you have a "partner" account, that is you don't own and don't have full control over the account you are attempting to access, you may not be able to query the photos without the owner granting you more permissive access.

**Comment by aninditaelagoon** [comment]
I get an array by printing $h = $client->LoadGroupHierarchy($username); line. 
Getting error in below line
$photos = $client->LoadPhotoSetPhotos($h->Elements[0]->Id, 0, $h->Elements[0]->PhotoCount);
Also the api access is open.
![image](https://user-images.githubusercontent.com/30255045/28313691-7087d12a-6bd5-11e7-948d-3f172677133a.png)

Is there any other way to set allow access for photos?

**Comment by lildude** [comment]
Yup, this sounds like you're using a partner account and don't have access to the first set in the array returned by `$h = $client->LoadGroupHierarchy($username);`.

This is a common problem seen when accessing photos with a partner account or other account without sufficient permissions on the galleries as seen in issues like https://github.com/lildude/phpZenfolio/issues/16 and https://github.com/lildude/phpZenfolio/issues/20, though it seems Zenfolio may have changed the error or is encountering some other issue.

It's not sufficient to have API access. The owner of the photos and gallery needs to grant the user you're using to access their photos with more access. This may be at the root level or on a per photoset level.

You may be able to determine which photosets you have access too by viewing the details of the array returned by `$h = $client->LoadGroupHierarchy($username);` and then modify the integer in `$photos = $client->LoadPhotoSetPhotos($h->Elements[0]->Id, 0, $h->Elements[0]->PhotoCount);`.  Assuming you have access to at least one photoset, you should eventually find and display the photos within it.

If you need more help with the privileges, I recommend you contact Zenfolio as they know their permissions structure better than I do.  

It might be worth contacting them to see why they're returning the unexpected error too.

**Comment by aninditaelagoon** [comment]
Thank you very much. I have contacted them. There is photo/gallery level access. they will email me those. Thank you so much for your great help.

**Comment by aninditaelagoon** [comment]
Need another help,please. As per your instruction When I am giving static galleryid, for example from http://www.zenfolio.com/monicahahnphotography/e/p98282304, gallery ID is "98282304". images are showing perfectly in $photos = $client->LoadPhotoSetPhotos('193621044', 0, '294');
![image](https://user-images.githubusercontent.com/30255045/28319413-791ed80e-6beb-11e7-8ea0-78ae22b56ca4.png)

It is working with all gallery ID. But when I am doing it dynamic, it is showing error. 
$photos = $client->LoadPhotoSetPhotos($h->Elements[0]->Id, 0, $h->Elements[0]->PhotoCount);
where $h->Elements[0]->Id is returning 5.7438253798626E+17 type of number
![image](https://user-images.githubusercontent.com/30255045/28319606-fa943bc2-6beb-11e7-9ff0-97648889dad2.png)

**Comment by aninditaelagoon** [comment]
![image](https://user-images.githubusercontent.com/30255045/28319729-58a8f720-6bec-11e7-87e5-ffa6d83012ce.png)

access is set to everyone for all the images.
![image](https://user-images.githubusercontent.com/30255045/28319764-7360e58c-6bec-11e7-8b0d-897dad057c04.png)

**Comment by lildude** [comment]
> It is working with all gallery ID. But when I am doing it dynamic, it is showing error.
> $photos = $client->LoadPhotoSetPhotos($h->Elements[0]->Id, 0, $h->Elements[0]->PhotoCount);
> where $h->Elements[0]->Id is returning 5.7438253798626E+17 type of number

Is `5.7438253798626E+17` the number you're getting back from the API for that element ID?  If so sounds like the Zenfolio API is sending back a very very big number which doesn't sound right. If it is, you'll need to ask Zenfolio about that huuge number.

**Comment by aninditaelagoon** [comment]
Need an urgent help. I use the 
[UploadUrl] => http://up.zenfolio.com/monicahahnphotography/p193621044/upload2.ushx
where I put the below code,
$photos = $client->LoadPhotoSetPhotos('193621044', 0, $h->Elements[0]->PhotoCount);
and get the data. But the problem is, the photos are coming from monicahahnphotography, not from zenfolio.  
http://monicahahnphotography.com/img/s2/v50/p800143486-1.jpg?sn=4X1&tk=7Ldj0bkaUzqiVsUq0S-PTO3xyLPd4C0K4Btwy0VAI0M=

I want the images to come from its core folder. For example
http://www.zenfolio.com/cdn/pub/6rhr1mgujado/0/null/mh/vgg8wgcl905a_dl93inv/s7/v165/p2381501363-3.jpg?ts=6VH&tk=_fPOKcuJEOFZfeTTHk51wVFltTCIz-R_8z1gvWVISg0=

How will I do that? Please help me out. I am working for a long day in it :(

**Comment by aninditaelagoon** [comment]
I can't able to post the array, because it is saying
You can't comment at this time — your comment is too long (maximum is 65536 characters).

**Comment by aninditaelagoon** [comment]
Is there anything related to 
$appname = 'monicahahnphotography/2.0 (http://dev1.elagoondigital.net/monicahahnphotography/php/)';
that's why it is not showing from zenfolio, on the ctrary it is showing from monicahahnphotography.com?
I dont want below url
http://monicahahnphotography.com/img/s2/v50/p800143486-1.jpg?sn=4X1&tk=7Ldj0bkaUzqiVsUq0S-PTO3xyLPd4C0K4Btwy0VAI0M=

I want below url, which directly come from zenfolio account
http://www.zenfolio.com/cdn/pub/6rhr1mgujado/0/null/mh/vgg8wgcl905a_dl93inv/s7/v165/p2381501363-3.jpg?ts=6VH&tk=_fPOKcuJEOFZfeTTHk51wVFltTCIz-R_8z1gvWVISg0=

Please help me out, please

**Comment by lildude** [comment]
How are you generating the URLs for each of the images?

If you use the `imageUrl` method I mentioned in https://github.com/lildude/phpZenfolio/issues/21 it should be using the correct URL as it uses the data received from the Zenfolio API.

**Comment by aninditaelagoon** [comment]
Yes I am using imageurl, but dont want to come it from monicahainphotography. I want it to come from zenfolio folder.

**Comment by lildude** [comment]
Ok, I've looked into this further and the images are _both_ being served from the Zenfolio servers:

http://monicahahnphotography.com/img/s2/v50/p800143486-1.jpg

... and ...

http://www.zenfolio.com/img/s2/v50/p800143486-1.jpg

... are the same photo served from the Zenfolio servers, just using different domain names.

As the Zenfolio account has been configured with the URL of `http://monicahahnphotography.com/`, all the content is hosted from that domain, including the pictures, which is on Zenfolio's servers.  This explains why the API is returning this as the photo host and is really the correct URL to use and also ensures you use the URLs at Zenfolio has documented at http://www.zenfolio.com/zf/help/api/guide/urls

I suspect this has been done deliberately by Zenfolio to help balance the load on their servers and allows them to make changes behind the scenes without affecting other people's sites.

With that in mind, I wouldn't recommend using a URL structure not documented or expressly supported by Zenfolio, like the `http://www.zenfolio.com/` domain you're attempting to use, because if they change something, for example block all access to user's photos accessed via the `zenfolio.com` domain name, your site _will_ break.

**Comment by aninditaelagoon** [comment]
Ok, I see.Let me look into it. Thanks so much for your help.

**Comment by lildude** [comment]
I think I can take the lack of further updates as confirmation I've answered your questions. Feel free to reopen if I haven't.
