### ISSUE TITLE
Raw file upload

### ISSUE THREAD

**Issue by gauravsp** [lildude/phpZenfolio#23]
Hi,

      I am using phpzenfolio api for uploading raw files to zenfolio.
      file format like dng work perfectly but getting below error for .svg and .eip format

Client error: `POST http://up.zenfolio.com/richardmourant/p578733668/raw.ushx?filename=demo-property-Raw_1.svg` resulted in a `400 Bad Request` response: Bad Request (Error Code: 400)

    Any suggestion will be really helpfull

**Comment by lildude** [comment]
Aaah, this is going to be a problem with the way phpZenfolio tries to determine the file type. At the moment it assumes all files uploaded are images as at the time, this was the only option available on Zenfolio.

I'll fix this this morning.

**Comment by lildude** [comment]
All fixed now. phpZenfolio 2.0.1 should work as you expect.
